apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::451788668908:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-ET1FSIFL03YL
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::451788668908:role/UdacityFlaskDeployCBKubectlRole
      username: build  
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-16T13:39:57Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1602"
  uid: fc5015de-4d53-4140-973c-a3fe2c7a8c32
